maintainer       "Alex Soto"
maintainer_email "apsoto@gmail.com"
license          "Apache 2.0"
description      "Installs/Configures sphinx search engine."
version          "0.5"
recipe           "sphinx"
depends "build-essential"
